services:
  ollama-cpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-cpu
    ports:
      - "1111:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      restart_policy:
        condition: always
      resources:
        limits:
          memory: 4G
    tty: true
    networks:
      - ollama-docker

volumes:
  ollama-data:
    driver: local

networks:
  ollama-docker:
    external: false
