name: Comment on PR Files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  comment-files:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requirements.txt

    - name: Run Python script
      run: python main.py
      env:
        ACTION_ACCESS_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
        REPOSITORY_OWNER: ${{ github.repository_owner }}
        REPOSITORY_NAME: ${{ github.event.pull_request.head.repo.name }}
        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        SOURCE_CODE_LANG: "python"
        AI_MODEL_NAME: "tinyllama"
        AI_MODEL_PORT: 1111
        AI_MODEL_PROMPT: "Provide a simple, short review for the code written below. You don't need to be very detalist, I just want a quick overview about the core idea of the code, and what it does."
        AI_MODEL_TEMPERATURE: 0.5
